// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"

namespace UIGameplayTags
{
	ESCAPEFROMHUMAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN ( UI_AnimalSelect );
	ESCAPEFROMHUMAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN ( UI_AnimalState );
	
	ESCAPEFROMHUMAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN ( UI_GameReady );
	ESCAPEFROMHUMAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN ( UI_GameState );
	ESCAPEFROMHUMAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN ( UI_GameEnd );
	ESCAPEFROMHUMAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN ( UI_GameInfo );
	ESCAPEFROMHUMAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN ( UI_GameSetting );

	ESCAPEFROMHUMAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN ( UI_GameStartLoading );
	ESCAPEFROMHUMAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN ( UI_GameEndLoading );
	ESCAPEFROMHUMAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN ( UI_SheepSkill );
	



}